import Header from '@/components/Header'
import type { Metadata } from 'next'
import { Work_Sans } from 'next/font/google'
import '@/styles/global.css'
import Container from '@/components/Container'
import { ThemeProvider } from '@/providers/ThemeProvider'
import Footer from '@/components/Footer'
import AuthProvider from '@/providers/AuthProvider'
const work = Work_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Test Blog",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={`${work.className} bg-white dark:bg-secondary-900`}>
				<AuthProvider>
					<ThemeProvider>
						<Container>
							<Header />
							{children}
						</Container>
						<Footer />
					</ThemeProvider>
				</AuthProvider>
			</body>
		</html>
	)
}
